// <auto-generated />
namespace Calendar.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FKClientToBillTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKClientToBillTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104290259245_FKClientToBillTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
